const CELL_WIDTH = 160;
const CELL_HEIGHT = 120;
const PADDING = 20;
const LABEL_HEIGHT = 18;
const MARGIN = 20;

const GRID_COLS = 3;
const GRID_ROWS = 6;

const GRID_W = GRID_COLS * CELL_WIDTH + (GRID_COLS - 1) * PADDING;
const GRID_H = GRID_ROWS * (CELL_HEIGHT + LABEL_HEIGHT) + (GRID_ROWS - 1) * PADDING;

const CANVAS_W = 2 * MARGIN + GRID_W;
const CANVAS_H = 2 * MARGIN + GRID_H;

const START_X = MARGIN;
const START_Y = MARGIN;

const PIXELATE_BLOCK = 5;
const BRIGHTNESS_FACTOR = 0.8;

const FILTER_NONE = 0;
const FILTER_GRAY = 1;
const FILTER_FLIP = 2;
const FILTER_PIXEL = 3;

export {
  CELL_WIDTH,
  CELL_HEIGHT,
  PADDING,
  LABEL_HEIGHT,
  MARGIN,
  GRID_COLS,
  GRID_ROWS,
  GRID_W,
  GRID_H,
  CANVAS_W,
  CANVAS_H,
  START_X,
  START_Y,
  PIXELATE_BLOCK,
  BRIGHTNESS_FACTOR,
  FILTER_NONE,
  FILTER_GRAY,
  FILTER_FLIP,
  FILTER_PIXEL
};
